// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXyZGMiguQOj6hwD8xecAL6Gkj_gh5Svg',
    appId: '1:959623989524:web:c4d7b413af96f71e045a01',
    messagingSenderId: '959623989524',
    projectId: 'azkare2026',
    authDomain: 'azkare2026.firebaseapp.com',
    storageBucket: 'azkare2026.firebasestorage.app',
    measurementId: 'G-63SCJ5M1MW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHDWAzliFgh8s6iNzoz8vOty3fCYV9BV0',
    appId: '1:959623989524:android:d74f1397ffa0d201045a01',
    messagingSenderId: '959623989524',
    projectId: 'azkare2026',
    storageBucket: 'azkare2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5hMRF1VqFHQ3dS8D2bwkMDwgXg1koNFg',
    appId: '1:959623989524:ios:5d0c10b08023a70e045a01',
    messagingSenderId: '959623989524',
    projectId: 'azkare2026',
    storageBucket: 'azkare2026.firebasestorage.app',
    iosBundleId: 'com.example.azkare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5hMRF1VqFHQ3dS8D2bwkMDwgXg1koNFg',
    appId: '1:959623989524:ios:5d0c10b08023a70e045a01',
    messagingSenderId: '959623989524',
    projectId: 'azkare2026',
    storageBucket: 'azkare2026.firebasestorage.app',
    iosBundleId: 'com.example.azkare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXyZGMiguQOj6hwD8xecAL6Gkj_gh5Svg',
    appId: '1:959623989524:web:62158ab36e523fee045a01',
    messagingSenderId: '959623989524',
    projectId: 'azkare2026',
    authDomain: 'azkare2026.firebaseapp.com',
    storageBucket: 'azkare2026.firebasestorage.app',
    measurementId: 'G-4Y4SJNP8VF',
  );
}
